export const newData =  [{
    'name': { 'value': 'Meta Mínima (R$)', 'id': 1 },
    'janeiro': { 'value': 0, 'id': 2 },
    'fevereiro': { 'value': 0, 'id': 3 },
    'março': { 'value': 0, 'id': 4 },
    'abril': { 'value': 0, 'id': 5 },
    'maio': { 'value': 0, 'id': 6 },
    'junho': { 'value': 0, 'id': 7 },
    'julho': { 'value': 0, 'id': 8 },
    'agosto': { 'value': 0, 'id': 9 },
    'setembro': { 'value': 0, 'id': 10 },
    'outubro': { 'value': 0, 'id': 11 },
    'novembro': { 'value': 0, 'id': 12 },
    'dezembro': { 'value': 0, 'id': 13 }
},
{
    'name': { 'value': 'Meta (R$)', 'id': 14 },
    'janeiro': { 'value': 0, 'id': 15 },
    'fevereiro': { 'value': 0, 'id': 16 },
    'março': { 'value': 0, 'id': 17 },
    'abril': { 'value': 0, 'id': 18 },
    'maio': { 'value': 0, 'id': 19 },
    'junho': { 'value': 0, 'id': 20 },
    'julho': { 'value': 0, 'id': 21 },
    'agosto': { 'value': 0, 'id': 22 },
    'setembro': { 'value': 0, 'id': 23 },
    'outubro': { 'value': 0, 'id': 24 },
    'novembro': { 'value': 0, 'id': 25 },
    'dezembro': { 'value': 0, 'id': 26 }
},
{
    'name': { 'value': 'Meta Heróica (R$)', 'id': 27 },
    'janeiro': { 'value': 0, 'id': 28 },
    'fevereiro': { 'value': 0, 'id': 29 },
    'março': { 'value': 0, 'id': 30 },
    'abril': { 'value': 0, 'id': 31 },
    'maio': { 'value': 0, 'id': 32 },
    'junho': { 'value': 0, 'id': 33 },
    'julho': { 'value': 0, 'id': 34 },
    'agosto': { 'value': 0, 'id': 35 },
    'setembro': { 'value': 0, 'id': 37 },
    'outubro': { 'value': 0, 'id': 38 },
    'novembro': { 'value': 0, 'id': 39 },
    'dezembro': { 'value': 0, 'id': 40 }
},
{
    'name': { 'value': 'Meta Mínima (Vol.)', 'id': 40 },
    'janeiro': { 'value': 0, 'id': 41 },
    'fevereiro': { 'value': 0, 'id': 42 },
    'março': { 'value': 0, 'id':43 },
    'abril': { 'value': 0, 'id': 44 },
    'maio': { 'value': 0, 'id': 45 },
    'junho': { 'value': 0, 'id': 46 },
    'julho': { 'value': 0, 'id': 47 },
    'agosto': { 'value': 0, 'id': 48 },
    'setembro': { 'value': 0, 'id': 49 },
    'outubro': { 'value': 0, 'id': 60 },
    'novembro': { 'value': 0, 'id': 61 },
    'dezembro': { 'value': 0, 'id': 62 }
},
{
    'name': { 'value': 'Meta (Vol.)', 'id': 63 },
    'janeiro': { 'value': 0, 'id': 64 },
    'fevereiro': { 'value': 0, 'id': 65 },
    'março': { 'value': 0, 'id': 66 },
    'abril': { 'value': 0, 'id': 67 },
    'maio': { 'value': 0, 'id': 68 },
    'junho': { 'value': 0, 'id': 68 },
    'julho': { 'value': 0, 'id': 69 },
    'agosto': { 'value': 0, 'id': 70 },
    'setembro': { 'value': 0, 'id': 71 },
    'outubro': { 'value': 0, 'id': 72 },
    'novembro': { 'value': 0, 'id': 73 },
    'dezembro': { 'value': 0, 'id': 74 }
},
{
    'name': { 'value': 'Meta Heróica (Vol.)', 'id': 75 },
    'janeiro': { 'value': 0, 'id': 76 },
    'fevereiro': { 'value': 0, 'id': 77 },
    'março': { 'value': 0, 'id': 78 },
    'abril': { 'value': 0, 'id': 79 },
    'maio': { 'value': 0, 'id': 80 },
    'junho': { 'value': 0, 'id': 81 },
    'julho': { 'value': 0, 'id': 82 },
    'agosto': { 'value': 0, 'id': 83 },
    'setembro': { 'value': 0, 'id': 84 },
    'outubro': { 'value': 0, 'id': 85 },
    'novembro': { 'value': 0, 'id': 86 },
    'dezembro': { 'value': 0, 'id': 87 }
},
{
    'name': { 'value': 'Ticket Médio Ml (R$)', 'id': 88 },
    'janeiro': { 'value': 0, 'id': 89 },
    'fevereiro': { 'value': 0, 'id': 90 },
    'março': { 'value': 0, 'id': 91 },
    'abril': { 'value': 0, 'id': 92 },
    'maio': { 'value': 0, 'id': 93 },
    'junho': { 'value': 0, 'id': 94 },
    'julho': { 'value': 0, 'id': 95 },
    'agosto': { 'value': 0, 'id': 96 },
    'setembro': { 'value': 0, 'id': 97 },
    'outubro': { 'value': 0, 'id': 98 },
    'novembro': { 'value': 0, 'id': 99 },
    'dezembro': { 'value': 0, 'id': 100 }
},
{
    'name': { 'value': 'Ticket Médio ME (R$)', 'id': 101 },
    'janeiro': { 'value': 0, 'id': 102 },
    'fevereiro': { 'value': 0, 'id': 103 },
    'março': { 'value': 0, 'id': 104 },
    'abril': { 'value': 0, 'id': 105 },
    'maio': { 'value': 0, 'id': 106 },
    'junho': { 'value': 0, 'id': 107 },
    'julho': { 'value': 0, 'id': 108 },
    'agosto': { 'value': 0, 'id': 109 },
    'setembro': { 'value': 0, 'id': 110 },
    'outubro': { 'value': 0, 'id': 111 },
    'novembro': { 'value': 0, 'id': 112 },
    'dezembro': { 'value': 0, 'id': 113 }
},
{
    'name': { 'value': 'Fat. por Cliente (R$)', 'id': 114 },
    'janeiro': { 'value': 0, 'id': 115 },
    'fevereiro': { 'value': 0, 'id': 116 },
    'março': { 'value': 0, 'id': 117 },
    'abril': { 'value': 0, 'id': 118 },
    'maio': { 'value': 0, 'id': 119 },
    'junho': { 'value': 0, 'id': 120 },
    'julho': { 'value': 0, 'id': 121 },
    'agosto': { 'value': 0, 'id': 122 },
    'setembro': { 'value': 0, 'id': 123 },
    'outubro': { 'value': 0, 'id': 124 },
    'novembro': { 'value': 0, 'id': 125 },
    'dezembro': { 'value': 0, 'id': 126 }
},
{
    'name': { 'value': 'Qtd. Cli. Positivado (R$)', 'id': 127 },
    'janeiro': { 'value': 0, 'id': 128 },
    'fevereiro': { 'value': 0, 'id': 129 },
    'março': { 'value': 0, 'id': 130 },
    'abril': { 'value': 0, 'id': 131 },
    'maio': { 'value': 0, 'id': 132 },
    'junho': { 'value': 0, 'id': 133 },
    'julho': { 'value': 0, 'id': 134 },
    'agosto': { 'value': 0, 'id': 135 },
    'setembro': { 'value': 0, 'id': 136 },
    'outubro': { 'value': 0, 'id': 137 },
    'novembro': { 'value': 0, 'id': 138 },
    'dezembro': { 'value': 0, 'id': 139 }
}]

export const newDataBackup = [
    { name: "Meta Mínima (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Meta (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Meta Heróica (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Meta Mínima (Vol.)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Meta (Vol.)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Meta Heróica (Vol.)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },

    { name: "Ticket Médio Ml (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Ticket Médio ME (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Fat. por Cliente (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
    { name: "Qtd. Cli. Positivado (R$)", janeiro: 0, fevereiro: 0, março: 0, abril: 0, maio: 0, junho: 0, julho: 0, agosto: 0, setembro: 0, outubro: 0, novembro: 0, dezembro: 0 },
]